### ISSUE TITLE
Some colors in the dark theme have contrast issues.

### ISSUE THREAD

**Issue by aspizu** [Biscuit-Colorscheme/biscuit#12] opened 2023-10-09 12:37 UTC

**Comment by tsukki9696** [comment] 2023-10-09 16:21
You know its hard to know what the issue is if you don't elaborate, right?

**Comment by tsukki9696** [comment] 2023-10-10 20:49
Closing it since OP hasnt elaborated on it further and its been a day

**Closed by tsukki9696** 2023-10-10 20:49 UTC
